default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: testing_app_development

test:
  <<: *default
  database: testing_app_test

production:
  <<: *default
  database: testing_app_production
  username: testing_app
  password: <%= ENV['DEMO_APP_DATABASE_PASSWORD'] %>
